language: node_js
sudo: required
git:
  submodules: true
node_js:
  - 10.16.0
branches:
  only:
    - master
cache: yarn
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
script:
  - yarn
  - yarn clean
  - yarn build
  - cd public/
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push -f https://${access_token}@github.com/wangxiuwen/linux-basic.git master:gh-pages
  - cd -
